version: 0.2
phases:
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore WMSWebAPI.csproj
  build:
    commands:
      - echo Build started on `date`
      - dotnet publish -c release -o WMSWebAPI.csproj

