version: 0.2

phases:
  install:
    commands:
      - dotnet restore
  pre_build:
    commands:
      - dotnet clean
  build:
    commands:
      - dotnet publish -c Release
  post_build:
    commands:
      - # Optional additional steps like creating artifacts
