version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET
      - yum install -y dotnet-sdk-8.0
  build:
    commands:
      - echo Building the .NET application...
      - dotnet build WMSWebAPI.csproj --configuration Release
  post_build:
    commands:
      - echo Build complete
artifacts:
  files:
    - '**/*'
  base-directory: 'bin/Release/net8.0'

