version: 0.2

phases:
  install:
   commands:
    - yum update -y
    - yum install -y dotnet-sdk-8.0
  pre_build:
    commands:
      - dotnet clean
  build:
    commands:
      - dotnet publish -c Release
  post_build:
    commands:
      - # Optional additional steps like creating artifacts
