version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo Installing dependencies...
      - dotnet restore
  pre_build:
    commands:
      - echo List contents of the current directory
      - ls -la
  build:
    commands:
      - echo "Building the application..."
      - dotnet build -c Release
      - echo "Publishing the application..."
      - dotnet publish -c Release -o ./published-app
  post_build:
    commands:
      - echo "Build and publish completed."
      - echo "Contents of the published-app directory:"
      - ls -la ./published-app
artifacts:
  files:
    - '**/*'
  base-directory: './published-app'
