version: 0.2

env:
  image: aws/codebuild/dotnet:8.0
  
phases:
  install:
    commands:
      - echo "Installing .NET 8 SDK"
  build:
    commands:
      - dotnet publish -c Release -o output
artifacts:
  files:
    - output/**/*
  base-directory: output


