version: 0.2

phases:
  install:
    commands:
      - echo Installing .NET SDK...
      - yum install -y dotnet-sdk-8.0
  build:
    commands:
      - echo Building the .NET project...
      - dotnet build .
  post_build:
    commands:
      - echo Build complete.


